"""empty message

Revision ID: 589c57fabbdd
Revises: 37c3308ba315
Create Date: 2022-11-14 01:54:34.281643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589c57fabbdd'
down_revision = '37c3308ba315'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
